version: '3.8'

services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d1r0pe7diees73fe5ee0-a.oregon-postgres.render.com:5432/library_db_5456
      SPRING_DATASOURCE_USERNAME: library_db_5456_user
      SPRING_DATASOURCE_PASSWORD: 8i0HafJaTLuaFowpnJNKo0pqzqe1JVlM
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
